<?php 
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
DB::table('modules')->insert(['level' => 'VAR','leadership_competence' => 'VAR','moscow' => 'VAR','domain' => 'VAR','leadership_sub_competence' => 'VAR','learn_url' => 'VAR','certificate_url' => 'VAR','course_date' => '.','role_id' => '11', 'description' => '.',]);
?>